apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-error503
spec:
  ports:
    - port: 80
  selector:
    app: error503
    release: {{.Release.Name}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-error503
spec:
  selector:
    matchLabels:
      app: error503
  replicas: 2
  strategy:
    type: {{ .Values.strategy }}
  template:
    metadata:
      labels:
        app: error503
        release: {{.Release.Name}}
    spec:
      containers:
        - name: main
          image: ondrejsika/training-example
          resources:
            requests:
              cpu: 20m
              memory: 30Mi
            limits:
              cpu: 50m
              memory: 60Mi
          ports:
            - containerPort: 80
